---

- name: 'Check ownership of home directories before removing.'
  loop: '{{ users_remove_list }}'
  register: 'users_remove_stats'
  stat:
    get_attributes: false
    get_checksum: false
    get_mime: false
    path: '{{ users_merged[item].home }}'

- name: 'Remove homedirs that exist and are owned by the to-be-removed user.'
  file:
    path: '{{ item.stat.path }}'
    state: 'absent'
  loop: '{{ users_remove_stats.results }}'
  when: >-
    item.stat is defined and
    item.stat.exists and
    item.stat.pw_name == item.item

- name: 'Remove user accounts.'
  loop: '{{ users_remove_list }}'
  user:
    name: '{{ item }}'
    state: 'absent'
  when: 'item == users_merged[item].user'
